name: hacker_kernel_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    get: ^4.6.6
    http: ^1.2.1
    image_picker: ^1.1.2
    shared_preferences: ^2.2.3
    uuid: ^4.4.0
    vibration: ^2.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
